name: holoviztrocas_panelapp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - ipykernel
  - pandas=0.25.1
  - geopandas=0.5.1
  - descartes
  - mapclassify
  - openpyxl
  - xlrd
  - cachey
  - marshmallow
  - webargs
  - fastparquet
  - python-snappy
  # holoviz packages
  - colorcet=2.0.1
  - datashader=0.7.0
  - geoviews=1.6.3
  - holoviews=1.12.5
  - hvplot=0.4.0
  - panel=0.6.2
  - param=1.9.1
