name: holoviztrocas_panelapp
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - ipykernel
  - pandas
  - geopandas
  - descartes
  - xlrd
  - fastparquet
  - python-snappy
  # holoviz packages
  - bokeh
  - colorcet
  - datashader
  - geoviews
  - holoviews
  - hvplot
  - panel
  - param
